language: cpp
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
compiler:
  - clang
  - gcc
env:
  - CXXFLAGS=-std=c++11
  - CXXFLAGS=-std=c++14
  - CXXFLAGS=-std=c++17
  - CXXFLAGS=-std=c++2a
  global:
  - CTEST_OUTPUT_ON_FAILURE=1
jobs:
  exclude:
    compiler: gcc
    env: CXXFLAGS=-std=c++2a
