language: cpp
script: make tests
compiler:
  - clang
  - gcc
env:
  - CXXFLAGS=-std=c++11
  - CXXFLAGS=-std=c++14
  - CXXFLAGS=-std=c++17
  - CXXFLAGS=-std=c++2a
jobs:
  exclude:
    compiler: gcc
    env: CXXFLAGS=-std=c++2a
