language: cpp
before_script:
  - mkdir build
  - cd build
  - cmake ..
script:
  - make
  - make test
compiler:
  - clang
  - gcc
env:
  global:
    - CTEST_OUTPUT_ON_FAILURE=1
  jobs:
    - CXXFLAGS=-std=c++11
    - CXXFLAGS=-std=c++14
    - CXXFLAGS=-std=c++17
    - CXXFLAGS=-std=c++2a
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os:
  - linux
  - osx
jobs:
  exclude:
    compiler: gcc
    env: CXXFLAGS=-std=c++2a
